### ISSUE TITLE
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.

### ISSUE THREAD

**Issue by ka28prit** [Autostronomy/AutoProf#5]
I'm working with @moustakas and we're trying to run the test cases but getting the following crash. Any suggestions?

```
% git log
commit e02d2be4a0a07e2b7eba64ed63599e73011389d0 (HEAD -> main, origin/main, origin/HEAD)
Author: Connor Stone <connorstone628@gmail.com>
Date:   Thu Jan 13 09:27:23 2022 -0500

% python -c "import matplotlib ; print(matplotlib.__version__)"
3.5.0
% python -c "import numpy ; print(numpy.__version__)"
1.21.2
% python -c "import astropy ; print(astropy.__version__)"
5.0
% python --version
Python 3.9.7

% autoprof test_batch_config.py Batch.log
testbatchimage3: head background at: 0.0 sec
testbatchimage2: head background at: 0.0 sec
testbatchimage1: head background at: 0.0 sec
testbatchimage4: head background at: 0.0 sec
testbatchimage3: head psf at: 5.8 sec
testbatchimage4: head psf at: 5.8 sec
testbatchimage2: head psf at: 5.8 sec
testbatchimage1: head psf at: 5.8 sec
ERROR:root:testbatchimage3: on step psf got error: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.
ERROR:root:testbatchimage4: on step psf got error: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.
ERROR:root:testbatchimage4: with full trace: Traceback (most recent call last):
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/Pipeline.py", line 169, in Process_Image
    dat, res = self.pipeline_methods[self.pipeline_steps[key][step]](dat, results, options)
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/pipeline_steps/PSF.py", line 204, in PSF_StarFind
    Plot_PSF_Stars(
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/autoprofutils/Diagnostic_Plots.py", line 82, in Plot_PSF_Stars
    LSBImage(IMG - results["background"], results["background noise"])
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/autoprofutils/SharedFunctions.py", line 76, in LSBImage
    plt.imshow(
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2640, in imshow
    __ret = gca().imshow(
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5447, in imshow
    im._scale_norm(norm, vmin, vmax)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/cm.py", line 380, in _scale_norm
    raise ValueError(
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.

ERROR:root:testbatchimage3: with full trace: Traceback (most recent call last):
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/Pipeline.py", line 169, in Process_Image
    dat, res = self.pipeline_methods[self.pipeline_steps[key][step]](dat, results, options)
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/pipeline_steps/PSF.py", line 204, in PSF_StarFind
    Plot_PSF_Stars(
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/autoprofutils/Diagnostic_Plots.py", line 82, in Plot_PSF_Stars
    LSBImage(IMG - results["background"], results["background noise"])
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/autoprofutils/SharedFunctions.py", line 76, in LSBImage
    plt.imshow(
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2640, in imshow
    __ret = gca().imshow(
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5447, in imshow
    im._scale_norm(norm, vmin, vmax)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/cm.py", line 380, in _scale_norm
    raise ValueError(
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.

ERROR:root:testbatchimage2: on step psf got error: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.
ERROR:root:testbatchimage1: on step psf got error: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.
ERROR:root:testbatchimage2: with full trace: Traceback (most recent call last):
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/Pipeline.py", line 169, in Process_Image
    dat, res = self.pipeline_methods[self.pipeline_steps[key][step]](dat, results, options)
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/pipeline_steps/PSF.py", line 204, in PSF_StarFind
    Plot_PSF_Stars(
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/autoprofutils/Diagnostic_Plots.py", line 82, in Plot_PSF_Stars
    LSBImage(IMG - results["background"], results["background noise"])
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/autoprofutils/SharedFunctions.py", line 76, in LSBImage
    plt.imshow(
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2640, in imshow
    __ret = gca().imshow(
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5447, in imshow
    im._scale_norm(norm, vmin, vmax)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/cm.py", line 380, in _scale_norm
    raise ValueError(
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.

ERROR:root:testbatchimage1: with full trace: Traceback (most recent call last):
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/Pipeline.py", line 169, in Process_Image
    dat, res = self.pipeline_methods[self.pipeline_steps[key][step]](dat, results, options)
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/pipeline_steps/PSF.py", line 204, in PSF_StarFind
    Plot_PSF_Stars(
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/autoprofutils/Diagnostic_Plots.py", line 82, in Plot_PSF_Stars
    LSBImage(IMG - results["background"], results["background noise"])
  File "/Users/keithpritchettjr./code/AutoProf/autoprof/autoprofutils/SharedFunctions.py", line 76, in LSBImage
    plt.imshow(
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2640, in imshow
    __ret = gca().imshow(
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5447, in imshow
    im._scale_norm(norm, vmin, vmax)
  File "/opt/anaconda3/envs/galaxyphot/lib/python3.9/site-packages/matplotlib/cm.py", line 380, in _scale_norm
    raise ValueError(
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.
```

**Comment by ConnorStoneAstro** [comment]
This has been a warning for a while and I guess it got upgraded to an error recently. I think I fixed it in the latest push to the main branch. Try pulling the latest version and let me know if you still get the error.

**Comment by ka28prit** [comment]
I pulled the latest version and it was a success! Thanks again for your assistance.

**Comment by ConnorStoneAstro** [comment]
Excellent! Happy to help!
